import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faTimes,
  faSave,
  faClock,
  faCalendar,
} from '@fortawesome/free-solid-svg-icons';
import { vacuumService } from '../../../services/vacuumService';
import { colors } from '../../../styles/colors';

interface VacuumConfigModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  config?: any | null;
  loading?: boolean;
}

const schema = yup.object({
  frecuencia: yup.string()
    .oneOf(['semanal', 'mensual'])
    .required('Selecciona una frecuencia'),
  hora_ejecucion: yup.string()
    .matches(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$/, 'Formato HH:MM:SS')
    .required('La hora de ejecución es requerida'),
  dia_semana: yup.number().when('frecuencia', {
    is: 'semanal',
    then: (schema) => schema.min(0).max(6).required('Selecciona un día'),
    otherwise: (schema) => schema.nullable().transform(() => null),
  }),
  dia_mes: yup.number().when('frecuencia', {
    is: 'mensual',
    then: (schema) => schema.min(1).max(31).required('Selecciona un día del mes'),
    otherwise: (schema) => schema.nullable().transform(() => null),
  }),
});

// Función para obtener el siguiente número de secuencia
const getNextSequenceNumber = async (frecuencia: string): Promise<number> => {
  try {
    const response = await vacuumService.getConfigs();
    const configs = response.configuraciones || [];
    
    const sameTypeConfigs = configs.filter((c: any) => c.frecuencia === frecuencia);
    
    const numbers = sameTypeConfigs.map((c: any) => {
      const match = c.nombre?.match(/_(\d+)$/);
      return match ? parseInt(match[1]) : 0;
    });
    
    const maxNumber = numbers.length > 0 ? Math.max(...numbers) : 0;
    return maxNumber + 1;
  } catch (error) {
    console.error('Error getting next sequence number:', error);
    return 1;
  }
};

// Generar nombre con secuencia automática
const generarNombreTarea = async (frecuencia: string, dia?: number): Promise<string> => {
  const secuencia = await getNextSequenceNumber(frecuencia);
  
  const frecuenciaMap: Record<string, string> = {
    semanal: 'semanal',
    mensual: 'mensual',
  };
  
  const frecuenciaLower = frecuenciaMap[frecuencia] || frecuencia;
  
  if (frecuencia === 'semanal' && dia !== undefined) {
    const dias = ['domingo', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado'];
    return `vacuum_${frecuenciaLower}_${dias[dia]}_${secuencia}`;
  }
  
  if (frecuencia === 'mensual' && dia !== undefined) {
    return `vacuum_${frecuenciaLower}_dia${dia}_${secuencia}`;
  }
  
  return `vacuum_${frecuenciaLower}_${secuencia}`;
};

export const VacuumConfigModal: React.FC<VacuumConfigModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  config,
  loading = false,
}) => {
  const [autoGeneratedName, setAutoGeneratedName] = useState('');
  const [generatingName, setGeneratingName] = useState(false);

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      frecuencia: 'semanal',
      hora_ejecucion: '02:00:00',
      dia_semana: 1,
      dia_mes: 1,
    },
  });

  const frecuencia = watch('frecuencia');
  const diaSemana = watch('dia_semana');
  const diaMes = watch('dia_mes');

  // Generar nombre automáticamente cuando cambian los campos
  useEffect(() => {
    const generateName = async () => {
      if (!config && isOpen) {
        setGeneratingName(true);
        try {
          let nombre = '';
          if (frecuencia === 'semanal') {
            nombre = await generarNombreTarea('semanal', diaSemana);
          } else if (frecuencia === 'mensual') {
            nombre = await generarNombreTarea('mensual', diaMes);
          }
          setAutoGeneratedName(nombre);
          setValue('nombre', nombre);
        } catch (error) {
          console.error('Error generating name:', error);
        } finally {
          setGeneratingName(false);
        }
      }
    };
    
    generateName();
  }, [frecuencia, diaSemana, diaMes, config, isOpen, setValue]);

  // Inicializar formulario cuando hay configuración existente
  useEffect(() => {
    if (!isOpen) return;

    if (config) {
      setAutoGeneratedName(config.nombre);
      reset({
        frecuencia: config.frecuencia,
        hora_ejecucion: config.hora_ejecucion,
        dia_semana: config.dia_semana ?? 1,
        dia_mes: config.dia_mes ?? 1,
      });
    } else {
      reset({
        frecuencia: 'semanal',
        hora_ejecucion: '02:00:00',
        dia_semana: 1,
        dia_mes: 1,
      });
    }
  }, [config, isOpen, reset]);

  const onSubmit = async (data: any) => {
    const submitData: any = {
      nombre: autoGeneratedName,
      frecuencia: data.frecuencia,
      hora_ejecucion: data.hora_ejecucion,
      tablas: [], // Siempre todas las tablas
      vacuum_analyze: true,
      vacuum_verbose: false,
    };

    if (data.frecuencia === 'semanal' && data.dia_semana !== undefined) {
      submitData.dia_semana = data.dia_semana;
    }

    if (data.frecuencia === 'mensual' && data.dia_mes !== undefined) {
      submitData.dia_mes = data.dia_mes;
    }

    try {
      if (config) {
        await vacuumService.updateConfig(config.id, submitData);
      } else {
        await vacuumService.createConfig(submitData);
      }
      onSuccess();
      onClose();
    } catch (error) {
      console.error('Error saving config:', error);
      alert('Error al guardar la configuración');
    }
  };

  if (!isOpen) return null;

  const modalOverlayStyle: React.CSSProperties = {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  };

  const modalContentStyle: React.CSSProperties = {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    width: '90%',
    maxWidth: '500px',
    maxHeight: '90vh',
    overflowY: 'auto',
    position: 'relative',
  };

  const formGroupStyle: React.CSSProperties = { marginBottom: '16px' };
  const rowStyle: React.CSSProperties = { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' };

  const labelStyle: React.CSSProperties = {
    display: 'block',
    marginBottom: '6px',
    fontSize: '14px',
    fontWeight: 500,
    color: colors.azulAcero,
  };

  const inputStyle = (hasError?: boolean): React.CSSProperties => ({
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${hasError ? '#EF4444' : '#E2E8F0'}`,
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: '#F8FAFC',
  });

  const selectStyle = (hasError?: boolean): React.CSSProperties => ({
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${hasError ? '#EF4444' : '#E2E8F0'}`,
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: 'white',
  });

  const namePreviewStyle: React.CSSProperties = {
    backgroundColor: `${colors.doradoClasico}10`,
    padding: '10px 12px',
    borderRadius: '8px',
    marginBottom: '20px',
    border: `1px solid ${colors.doradoClasico}30`,
  };

  const modalFooterStyle: React.CSSProperties = {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '24px',
    paddingTop: '16px',
    borderTop: '1px solid #EDF2F7',
  };

  const buttonStyle = (variant: 'primary' | 'secondary'): React.CSSProperties => ({
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    backgroundColor: variant === 'primary' ? colors.doradoClasico : '#E2E8F0',
    color: variant === 'primary' ? 'white' : '#475569',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  });

  return (
    <div style={modalOverlayStyle} onClick={onClose}>
      <div style={modalContentStyle} onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
          <h3 style={{ fontSize: '18px', fontWeight: 600, color: colors.negroSuave }}>
            {config ? 'Editar Tarea' : 'Nueva Tarea'}
          </h3>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
            <FontAwesomeIcon icon={faTimes} style={{ color: '#718096', fontSize: '18px' }} />
          </button>
        </div>

        <form onSubmit={handleSubmit(onSubmit)}>
          <div style={namePreviewStyle}>
            <div style={{ fontSize: '12px', color: colors.azulAcero, marginBottom: '4px' }}>
              <FontAwesomeIcon icon={faClock} style={{ marginRight: '4px' }} />
              Nombre de la tarea (generado automáticamente)
            </div>
            <div style={{ fontSize: '14px', fontWeight: 500, color: colors.doradoClasico }}>
              {generatingName ? 'Generando...' : autoGeneratedName || 'Se generará al guardar'}
            </div>
          </div>

          <div style={rowStyle}>
            <div style={formGroupStyle}>
              <label style={labelStyle}>Frecuencia *</label>
              <select style={selectStyle(!!errors.frecuencia)} {...register('frecuencia')}>
                <option value="semanal">Semanal</option>
                <option value="mensual">Mensual</option>
              </select>
            </div>

            <div style={formGroupStyle}>
              <label style={labelStyle}>Hora de ejecución *</label>
              <input
                type="text"
                style={inputStyle(!!errors.hora_ejecucion)}
                {...register('hora_ejecucion')}
                placeholder="02:00:00"
              />
            </div>
          </div>

          {frecuencia === 'semanal' && (
            <div style={formGroupStyle}>
              <label style={labelStyle}>Día de la semana *</label>
              <select style={selectStyle(!!errors.dia_semana)} {...register('dia_semana', { valueAsNumber: true })}>
                <option value={0}>Domingo</option>
                <option value={1}>Lunes</option>
                <option value={2}>Martes</option>
                <option value={3}>Miércoles</option>
                <option value={4}>Jueves</option>
                <option value={5}>Viernes</option>
                <option value={6}>Sábado</option>
              </select>
            </div>
          )}

          {frecuencia === 'mensual' && (
            <div style={formGroupStyle}>
              <label style={labelStyle}>Día del mes *</label>
              <input
                type="number"
                min="1"
                max="31"
                style={inputStyle(!!errors.dia_mes)}
                {...register('dia_mes', { valueAsNumber: true })}
              />
            </div>
          )}

          <div style={modalFooterStyle}>
            <button type="button" style={buttonStyle('secondary')} onClick={onClose}>
              Cancelar
            </button>
            <button type="submit" style={buttonStyle('primary')} disabled={loading}>
              <FontAwesomeIcon icon={faSave} />
              {loading ? 'Guardando...' : config ? 'Actualizar' : 'Crear'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};