import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faTimes,
  faSave,
  faClock,
  faCalendar,
  faTable,
  faCheckSquare,
  faSquare,
} from '@fortawesome/free-solid-svg-icons';
import { vacuumService } from '../../../services/vacuumService';
import { backupService } from '../../../services/backupService';
import type { TablaInfo } from '../../../types/backup';
import { colors } from '../../../styles/colors';

interface VacuumConfigModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  config?: any | null;
  loading?: boolean;
}

const schema = yup.object({
  nombre: yup.string()
    .required('El nombre es requerido')
    .min(3, 'Mínimo 3 caracteres'),
  frecuencia: yup.string()
    .oneOf(['diario', 'semanal', 'mensual'])
    .required('Selecciona una frecuencia'),
  hora_ejecucion: yup.string()
    .matches(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$/, 'Formato HH:MM:SS')
    .required('La hora de ejecución es requerida'),
  dia_semana: yup.number().when('frecuencia', {
    is: 'semanal',
    then: (schema) => schema.min(0).max(6).required('Selecciona un día'),
    otherwise: (schema) => schema.nullable().transform(() => null),
  }),
  dia_mes: yup.number().when('frecuencia', {
    is: 'mensual',
    then: (schema) => schema.min(1).max(31).required('Selecciona un día del mes'),
    otherwise: (schema) => schema.nullable().transform(() => null),
  }),
});

const generarNombreTarea = (frecuencia: string, hora: string, dia?: number): string => {
  const fecha = new Date();
  const timestamp = fecha.toISOString().slice(0, 19).replace(/:/g, '-');

  const frecuenciaMap: Record<string, string> = {
    diario: 'Diario',
    semanal: 'Semanal',
    mensual: 'Mensual',
  };

  let nombreBase = `Vacuum_${frecuenciaMap[frecuencia] ?? frecuencia}_${timestamp}`;

  if (frecuencia === 'semanal' && dia !== undefined && !isNaN(dia)) {
    const dias = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'];
    nombreBase = `Vacuum_Semanal_${dias[dia]}_${timestamp}`;
  }

  if (frecuencia === 'mensual' && dia !== undefined && !isNaN(dia)) {
    nombreBase = `Vacuum_Mensual_Dia${dia}_${timestamp}`;
  }

  return nombreBase;
};

export const VacuumConfigModal: React.FC<VacuumConfigModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  config,
  loading = false,
}) => {
  const [tablas, setTablas] = useState<TablaInfo[]>([]);
  const [selectedTables, setSelectedTables] = useState<Set<string>>(new Set());
  const [runAllTables, setRunAllTables] = useState(true);
  const [autoGeneratedName, setAutoGeneratedName] = useState('');
  const [loadingTables, setLoadingTables] = useState(false);

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      nombre: '',
      frecuencia: 'diario',
      hora_ejecucion: '02:00:00',
      dia_semana: 0,
      dia_mes: 1,
    },
  });

  const frecuencia = watch('frecuencia');
  const horaEjecucion = watch('hora_ejecucion');
  const diaSemana = watch('dia_semana');
  const diaMes = watch('dia_mes');

  // Cargar tablas cuando abre el modal
  useEffect(() => {
    if (isOpen) {
      loadTables();
    }
  }, [isOpen]);

  // Inicializar formulario cuando cambia config o se abre el modal
  useEffect(() => {
    if (!isOpen) return;

    if (config) {
      const nombre = config.nombre;
      setAutoGeneratedName(nombre);
      reset({
        nombre,
        frecuencia: config.frecuencia,
        hora_ejecucion: config.hora_ejecucion,
        dia_semana: config.dia_semana ?? 0,
        dia_mes: config.dia_mes ?? 1,
      });

      if (config.tablas && config.tablas.length > 0) {
        setRunAllTables(false);
        setSelectedTables(new Set(config.tablas));
      } else {
        setRunAllTables(true);
        setSelectedTables(new Set());
      }
    } else {
      const nombre = generarNombreTarea('diario', '02:00:00');
      setAutoGeneratedName(nombre);
      reset({
        nombre,
        frecuencia: 'diario',
        hora_ejecucion: '02:00:00',
        dia_semana: 0,
        dia_mes: 1,
      });
      setRunAllTables(true);
      setSelectedTables(new Set());
    }
  }, [config, isOpen]);

  // Actualizar nombre automático cuando cambian los campos (solo en modo creación)
  useEffect(() => {
    if (config) return;

    const dia = frecuencia === 'semanal' ? diaSemana : frecuencia === 'mensual' ? diaMes : undefined;
    const nombre = generarNombreTarea(frecuencia, horaEjecucion, dia);
    setAutoGeneratedName(nombre);
    setValue('nombre', nombre, { shouldValidate: true });
  }, [frecuencia, horaEjecucion, diaSemana, diaMes]);

  const loadTables = async () => {
    setLoadingTables(true);
    try {
      const data = await backupService.getTables();
      setTablas(data);
    } catch (error) {
      console.error('Error loading tables:', error);
    } finally {
      setLoadingTables(false);
    }
  };

  const handleSelectAll = () => {
    if (selectedTables.size === tablas.length) {
      setSelectedTables(new Set());
    } else {
      setSelectedTables(new Set(tablas.map(t => t.table_name)));
    }
  };

  const handleToggleTable = (tableName: string) => {
    const newSelected = new Set(selectedTables);
    if (newSelected.has(tableName)) {
      newSelected.delete(tableName);
    } else {
      newSelected.add(tableName);
    }
    setSelectedTables(newSelected);
  };

  const onSubmit = async (data: any) => {
    const submitData: any = {
      nombre: autoGeneratedName,
      frecuencia: data.frecuencia,
      hora_ejecucion: data.hora_ejecucion,
      retencion_dias: 30,
      tablas: runAllTables ? [] : Array.from(selectedTables),
    };

    if (data.frecuencia === 'semanal' && data.dia_semana !== undefined) {
      submitData.dia_semana = data.dia_semana;
    }

    if (data.frecuencia === 'mensual' && data.dia_mes !== undefined) {
      submitData.dia_mes = data.dia_mes;
    }

    try {
      if (config) {
        await vacuumService.updateConfig(config.id, submitData);
      } else {
        await vacuumService.createConfig(submitData);
      }
      onSuccess();
      onClose();
    } catch (error) {
      console.error('Error saving config:', error);
      alert('Error al guardar la configuración');
    }
  };

  const onError = (errors: any) => {
    console.error('❌ Errores de validación:', errors);
  };

  if (!isOpen) return null;

  const modalOverlayStyle: React.CSSProperties = {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  };

  const modalContentStyle: React.CSSProperties = {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    width: '90%',
    maxWidth: '600px',
    maxHeight: '90vh',
    overflowY: 'auto',
    position: 'relative',
  };

  const formGroupStyle: React.CSSProperties = { marginBottom: '16px' };

  const labelStyle: React.CSSProperties = {
    display: 'block',
    marginBottom: '6px',
    fontSize: '14px',
    fontWeight: 500,
    color: colors.azulAcero,
  };

  const inputStyle = (hasError?: boolean): React.CSSProperties => ({
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${hasError ? '#EF4444' : '#E2E8F0'}`,
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: '#F8FAFC',
  });

  const selectStyle = (hasError?: boolean): React.CSSProperties => ({
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${hasError ? '#EF4444' : '#E2E8F0'}`,
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: 'white',
  });

  const rowStyle: React.CSSProperties = {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  };

  const optionStyle = (isSelected: boolean): React.CSSProperties => ({
    padding: '12px',
    borderRadius: '10px',
    border: `2px solid ${isSelected ? colors.doradoClasico : '#E2E8F0'}`,
    backgroundColor: isSelected ? `${colors.doradoClasico}10` : 'white',
    cursor: 'pointer',
    textAlign: 'center',
  });

  const tablesContainerStyle: React.CSSProperties = {
    maxHeight: '200px',
    overflowY: 'auto',
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    marginTop: '12px',
  };

  const tableItemStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 12px',
    borderBottom: '1px solid #E2E8F0',
    cursor: 'pointer',
  };

  const namePreviewStyle: React.CSSProperties = {
    backgroundColor: `${colors.doradoClasico}10`,
    padding: '10px 12px',
    borderRadius: '8px',
    marginBottom: '20px',
    border: `1px solid ${colors.doradoClasico}30`,
  };

  const modalFooterStyle: React.CSSProperties = {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '24px',
    paddingTop: '16px',
    borderTop: '1px solid #EDF2F7',
  };

  const buttonStyle = (variant: 'primary' | 'secondary'): React.CSSProperties => ({
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    backgroundColor: variant === 'primary' ? colors.doradoClasico : '#E2E8F0',
    color: variant === 'primary' ? 'white' : '#475569',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  });

  return (
    <div style={modalOverlayStyle} onClick={onClose}>
      <div style={modalContentStyle} onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
          <h3 style={{ fontSize: '18px', fontWeight: 600, color: colors.negroSuave }}>
            {config ? 'Editar Tarea Automatizada' : 'Nueva Tarea Automatizada'}
          </h3>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
            <FontAwesomeIcon icon={faTimes} style={{ color: '#718096', fontSize: '18px' }} />
          </button>
        </div>

        <form onSubmit={handleSubmit(onSubmit, onError)}>
          <div style={namePreviewStyle}>
            <div style={{ fontSize: '12px', color: colors.azulAcero, marginBottom: '4px' }}>
              <FontAwesomeIcon icon={faClock} style={{ marginRight: '4px' }} />
              Nombre de la tarea (generado automáticamente)
            </div>
            <div style={{ fontSize: '14px', fontWeight: 500, color: colors.doradoClasico }}>
              {autoGeneratedName || 'Se generará al guardar'}
            </div>
          </div>

          <div style={rowStyle}>
            <div style={formGroupStyle}>
              <label style={labelStyle}>Frecuencia *</label>
              <select style={selectStyle(!!errors.frecuencia)} {...register('frecuencia')}>
                <option value="diario">Diario</option>
                <option value="semanal">Semanal</option>
                <option value="mensual">Mensual</option>
              </select>
              {errors.frecuencia && <span style={{ color: '#EF4444', fontSize: '12px' }}>{errors.frecuencia.message}</span>}
            </div>

            <div style={formGroupStyle}>
              <label style={labelStyle}>Hora de ejecución *</label>
              <input
                type="text"
                style={inputStyle(!!errors.hora_ejecucion)}
                {...register('hora_ejecucion')}
                placeholder="02:00:00"
              />
              {errors.hora_ejecucion && <span style={{ color: '#EF4444', fontSize: '12px' }}>{errors.hora_ejecucion.message}</span>}
            </div>
          </div>

          {frecuencia === 'semanal' && (
            <div style={formGroupStyle}>
              <label style={labelStyle}>Día de la semana *</label>
              <select style={selectStyle(!!errors.dia_semana)} {...register('dia_semana', { valueAsNumber: true })}>
                <option value={0}>Domingo</option>
                <option value={1}>Lunes</option>
                <option value={2}>Martes</option>
                <option value={3}>Miércoles</option>
                <option value={4}>Jueves</option>
                <option value={5}>Viernes</option>
                <option value={6}>Sábado</option>
              </select>
              {errors.dia_semana && <span style={{ color: '#EF4444', fontSize: '12px' }}>{errors.dia_semana.message}</span>}
            </div>
          )}

          {frecuencia === 'mensual' && (
            <div style={formGroupStyle}>
              <label style={labelStyle}>Día del mes *</label>
              <input
                type="number"
                min="1"
                max="31"
                style={inputStyle(!!errors.dia_mes)}
                {...register('dia_mes', { valueAsNumber: true })}
              />
              {errors.dia_mes && <span style={{ color: '#EF4444', fontSize: '12px' }}>{errors.dia_mes.message}</span>}
            </div>
          )}

          <div style={formGroupStyle}>
            <label style={labelStyle}>¿Qué optimizar?</label>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
              <div style={optionStyle(runAllTables)} onClick={() => setRunAllTables(true)}>
                <div style={{ fontWeight: 600 }}>Todas las tablas</div>
                <div style={{ fontSize: '12px', color: '#718096' }}>Optimizar toda la BD</div>
              </div>
              <div style={optionStyle(!runAllTables)} onClick={() => setRunAllTables(false)}>
                <div style={{ fontWeight: 600 }}>Tablas específicas</div>
                <div style={{ fontSize: '12px', color: '#718096' }}>Seleccionar tablas</div>
              </div>
            </div>

            {!runAllTables && (
              <>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <label style={labelStyle}>Seleccionar tablas</label>
                  <button
                    type="button"
                    onClick={handleSelectAll}
                    style={{ fontSize: '12px', color: colors.doradoClasico, background: 'none', border: 'none', cursor: 'pointer' }}
                  >
                    {selectedTables.size === tablas.length ? 'Deseleccionar todas' : 'Seleccionar todas'}
                  </button>
                </div>

                {loadingTables ? (
                  <div style={{ textAlign: 'center', padding: '20px' }}>Cargando tablas...</div>
                ) : (
                  <div style={tablesContainerStyle}>
                    {tablas.map((tabla) => {
                      const isSelected = selectedTables.has(tabla.table_name);
                      return (
                        <div key={tabla.table_name} style={tableItemStyle} onClick={() => handleToggleTable(tabla.table_name)}>
                          <FontAwesomeIcon
                            icon={isSelected ? faCheckSquare : faSquare}
                            style={{ color: isSelected ? colors.doradoClasico : '#A0AEC0' }}
                          />
                          <span>{tabla.table_name}</span>
                        </div>
                      );
                    })}
                  </div>
                )}
              </>
            )}
          </div>

          <div style={modalFooterStyle}>
            <button type="button" style={buttonStyle('secondary')} onClick={onClose}>
              Cancelar
            </button>
            <button type="submit" style={buttonStyle('primary')} disabled={loading}>
              <FontAwesomeIcon icon={faSave} />
              {loading ? 'Guardando...' : config ? 'Actualizar' : 'Crear'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};