import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faTimes,
  faSave,
  faClock,
  faCalendar,
  faTable,
  faCheckSquare,
  faSquare,
} from '@fortawesome/free-solid-svg-icons';
import { backupService } from '../../../services/backupService';
import type { TablaInfo } from '../../../types/backup';
import { colors } from '../../../styles/colors';

interface ScheduledTaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  config?: any | null;
  loading?: boolean;
}

// ✅ FIX 1: Los valores del .when() ahora coinciden exactamente con los <option value>
const schema = yup.object({
  frecuencia: yup.string()
    .oneOf(['Diario', 'Semanal', 'Mensual'])
    .required('Selecciona una frecuencia'),
  hora_ejecucion: yup.string()
    .matches(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$/, 'Formato HH:MM:SS')
    .required('La hora de ejecución es requerida'),
  dia_semana: yup.number().when('frecuencia', {
    is: 'Semanal', // ✅ Antes era 'semanal' (minúscula) — no coincidía con el value del select
    then: (schema) => schema.min(0).max(6).required('Selecciona un día'),
    otherwise: (schema) => schema.nullable().transform(() => null), // ✅ Limpia el valor cuando no aplica
  }),
  dia_mes: yup.number().when('frecuencia', {
    is: 'Mensual', // ✅ Antes era 'mensual' (minúscula) — no coincidía con el value del select
    then: (schema) => schema.min(1).max(31).required('Selecciona un día del mes'),
    otherwise: (schema) => schema.nullable().transform(() => null), // ✅ Limpia el valor cuando no aplica
  }),
  retencion_dias: yup.number()
    .min(1, 'Mínimo 1 día')
    .max(365, 'Máximo 365 días')
    .default(30),
});

// Función para generar nombre automático de la tarea
const generarNombreTarea = (frecuencia: string, hora: string, dia?: number): string => {
  const fecha = new Date();
  const timestamp = fecha.toISOString().slice(0, 19).replace(/:/g, '-');

  const frecuenciaMap: Record<string, string> = {
    Diario: 'Diario',
    Semanal: 'Semanal',
    Mensual: 'Mensual',
  };

  let nombreBase = `Backup_${frecuenciaMap[frecuencia]}_${timestamp}`;

  if (frecuencia === 'Semanal' && dia !== undefined) {
    const dias = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'];
    nombreBase = `Backup_${frecuenciaMap[frecuencia]}_${dias[dia]}_${timestamp}`;
  }

  if (frecuencia === 'Mensual' && dia !== undefined) {
    nombreBase = `Backup_${frecuenciaMap[frecuencia]}_Dia${dia}_${timestamp}`;
  }

  return nombreBase;
};

export const ScheduledTaskModal: React.FC<ScheduledTaskModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  config,
  loading = false,
}) => {
  const [backupType, setBackupType] = useState<'completo' | 'parcial'>('completo');
  const [tablas, setTablas] = useState<TablaInfo[]>([]);
  const [selectedTables, setSelectedTables] = useState<Set<string>>(new Set());
  const [loadingTables, setLoadingTables] = useState(false);
  const [autoGeneratedName, setAutoGeneratedName] = useState('');

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      frecuencia: 'Diario',
      hora_ejecucion: '02:00:00',
      retencion_dias: 30,
      dia_semana: 1,  // ✅ FIX 2: Default definido para evitar undefined en validación
      dia_mes: 1,     // ✅ FIX 2: Default definido para evitar undefined en validación
    },
  });

  const frecuencia = watch('frecuencia');
  const horaEjecucion = watch('hora_ejecucion');
  const diaSemana = watch('dia_semana');
  const diaMes = watch('dia_mes');

  // ✅ FIX 3: Corregida inconsistencia de mayúsculas en generarNombreTarea
  useEffect(() => {
    if (!config) {
      let nombre = '';
      if (frecuencia === 'Diario') {
        nombre = generarNombreTarea('Diario', horaEjecucion);
      } else if (frecuencia === 'Semanal') {
        nombre = generarNombreTarea('Semanal', horaEjecucion, diaSemana); // ✅ Antes era 'semanal'
      } else if (frecuencia === 'Mensual') {
        nombre = generarNombreTarea('Mensual', horaEjecucion, diaMes); // ✅ Antes era 'mensual'
      }
      setAutoGeneratedName(nombre);
    }
  }, [frecuencia, horaEjecucion, diaSemana, diaMes, config]);

  useEffect(() => {
    if (isOpen) {
      loadTables();
    }
  }, [isOpen]);

  useEffect(() => {
    if (config) {
      setValue('frecuencia', config.frecuencia);
      setValue('hora_ejecucion', config.hora_ejecucion);
      setValue('dia_semana', config.dia_semana ?? 1);   // ✅ fallback a 1 si es null
      setValue('dia_mes', config.dia_mes ?? 1);         // ✅ fallback a 1 si es null
      setValue('retencion_dias', config.retencion_dias);
      setAutoGeneratedName(config.nombre);

      if (config.incluir_tablas && config.incluir_tablas.length > 0) {
        setBackupType('parcial');
        setSelectedTables(new Set(config.incluir_tablas));
      } else {
        setBackupType('completo');
        setSelectedTables(new Set());
      }
    } else {
      reset({
        frecuencia: 'Diario',
        hora_ejecucion: '02:00:00',
        retencion_dias: 30,
        dia_semana: 1,  // ✅ Reset con defaults explícitos
        dia_mes: 1,
      });
      setBackupType('completo');
      setSelectedTables(new Set());
    }
  }, [config, isOpen, setValue, reset]);

  const loadTables = async () => {
    setLoadingTables(true);
    try {
      const data = await backupService.getTables();
      setTablas(data);
    } catch (error) {
      console.error('Error loading tables:', error);
    } finally {
      setLoadingTables(false);
    }
  };

  const handleSelectAll = () => {
    if (selectedTables.size === tablas.length) {
      setSelectedTables(new Set());
    } else {
      setSelectedTables(new Set(tablas.map(t => t.table_name)));
    }
  };

  const handleToggleTable = (tableName: string) => {
    const newSelected = new Set(selectedTables);
    if (newSelected.has(tableName)) {
      newSelected.delete(tableName);
    } else {
      newSelected.add(tableName);
    }
    setSelectedTables(newSelected);
  };

  const onSubmit = async (data: any) => {
    const submitData: any = {
      ...data,
      nombre: autoGeneratedName,
      incluir_tablas: backupType === 'parcial' ? Array.from(selectedTables) : [],
      notificar_email: false,
      emails_notificacion: [],
    };

    if (config) {
      await backupService.updateConfig(config.id, submitData);
    } else {
      await backupService.createConfig(submitData);
    }
    onSuccess();
    onClose();
  };

  if (!isOpen) return null;

  const modalOverlayStyle: React.CSSProperties = {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  };

  const modalContentStyle: React.CSSProperties = {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    width: '90%',
    maxWidth: '600px',
    maxHeight: '90vh',
    overflowY: 'auto',
    position: 'relative',
  };

  const modalHeaderStyle: React.CSSProperties = {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  };

  const modalTitleStyle: React.CSSProperties = {
    fontSize: '18px',
    fontWeight: 600,
    color: colors.negroSuave,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  };

  const formGroupStyle: React.CSSProperties = {
    marginBottom: '16px',
  };

  const labelStyle: React.CSSProperties = {
    display: 'block',
    marginBottom: '6px',
    fontSize: '14px',
    fontWeight: 500,
    color: colors.azulAcero,
  };

  const inputStyle = (hasError?: boolean): React.CSSProperties => ({
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${hasError ? '#EF4444' : '#E2E8F0'}`,
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: '#F8FAFC',
    boxSizing: 'border-box',
  });

  const selectStyle = (hasError?: boolean): React.CSSProperties => ({
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${hasError ? '#EF4444' : '#E2E8F0'}`,
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: 'white',
    boxSizing: 'border-box',
  });

  const rowStyle: React.CSSProperties = {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  };

  const optionStyle = (isSelected: boolean): React.CSSProperties => ({
    padding: '12px',
    borderRadius: '10px',
    border: `2px solid ${isSelected ? colors.doradoClasico : '#E2E8F0'}`,
    backgroundColor: isSelected ? `${colors.doradoClasico}10` : 'white',
    cursor: 'pointer',
    textAlign: 'center',
    transition: 'all 0.2s',
  });

  const tablesContainerStyle: React.CSSProperties = {
    maxHeight: '200px',
    overflowY: 'auto',
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    marginTop: '12px',
  };

  const tableItemStyle = (isSelected: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 12px',
    borderBottom: '1px solid #E2E8F0',
    cursor: 'pointer',
    backgroundColor: isSelected ? `${colors.doradoClasico}08` : 'transparent',
    transition: 'background-color 0.15s',
  });

  const modalFooterStyle: React.CSSProperties = {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '24px',
    paddingTop: '16px',
    borderTop: '1px solid #EDF2F7',
  };

  const buttonStyle = (variant: 'primary' | 'secondary', disabled?: boolean): React.CSSProperties => ({
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 500,
    cursor: disabled ? 'not-allowed' : 'pointer',
    backgroundColor: variant === 'primary'
      ? disabled ? '#C9B97A' : colors.doradoClasico
      : '#E2E8F0',
    color: variant === 'primary' ? 'white' : '#475569',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    opacity: disabled ? 0.7 : 1,
    transition: 'opacity 0.2s',
  });

  const namePreviewStyle: React.CSSProperties = {
    backgroundColor: `${colors.doradoClasico}10`,
    padding: '10px 12px',
    borderRadius: '8px',
    marginBottom: '20px',
    border: `1px solid ${colors.doradoClasico}30`,
  };

  const errorTextStyle: React.CSSProperties = {
    color: '#EF4444',
    fontSize: '12px',
    marginTop: '4px',
  };

  return (
    <div style={modalOverlayStyle} onClick={onClose}>
      <div style={modalContentStyle} onClick={(e) => e.stopPropagation()}>
        <div style={modalHeaderStyle}>
          <h3 style={modalTitleStyle}>
            <FontAwesomeIcon icon={faCalendar} style={{ color: colors.doradoClasico }} />
            {config ? 'Editar Tarea Automatizada' : 'Nueva Tarea Automatizada'}
          </h3>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
            <FontAwesomeIcon icon={faTimes} style={{ color: '#718096', fontSize: '18px' }} />
          </button>
        </div>

        <form onSubmit={handleSubmit(onSubmit)}>
          {/* Nombre generado automáticamente */}
          <div style={namePreviewStyle}>
            <div style={{ fontSize: '12px', color: colors.azulAcero, marginBottom: '4px' }}>
              <FontAwesomeIcon icon={faClock} style={{ marginRight: '4px' }} />
              Nombre de la tarea (generado automáticamente)
            </div>
            <div style={{ fontSize: '14px', fontWeight: 500, color: colors.doradoClasico }}>
              {autoGeneratedName || 'Se generará al guardar'}
            </div>
          </div>

          <div style={rowStyle}>
            <div style={formGroupStyle}>
              <label style={labelStyle}>Frecuencia *</label>
              <select style={selectStyle(!!errors.frecuencia)} {...register('frecuencia')}>
                <option value="Diario">Diario</option>
                <option value="Semanal">Semanal</option>
                <option value="Mensual">Mensual</option>
              </select>
              {errors.frecuencia && <p style={errorTextStyle}>{errors.frecuencia.message}</p>}
            </div>

            <div style={formGroupStyle}>
              <label style={labelStyle}>Hora de ejecución *</label>
              <input
                type="text"
                style={inputStyle(!!errors.hora_ejecucion)}
                {...register('hora_ejecucion')}
                placeholder="02:00:00"
              />
              {errors.hora_ejecucion && <p style={errorTextStyle}>{errors.hora_ejecucion.message}</p>}
            </div>
          </div>

          {frecuencia === 'Semanal' && (
            <div style={formGroupStyle}>
              <label style={labelStyle}>Día de la semana *</label>
              <select
                style={selectStyle(!!errors.dia_semana)}
                {...register('dia_semana', { valueAsNumber: true })}
              >
                <option value={0}>Domingo</option>
                <option value={1}>Lunes</option>
                <option value={2}>Martes</option>
                <option value={3}>Miércoles</option>
                <option value={4}>Jueves</option>
                <option value={5}>Viernes</option>
                <option value={6}>Sábado</option>
              </select>
              {errors.dia_semana && <p style={errorTextStyle}>{errors.dia_semana.message}</p>}
            </div>
          )}

          {frecuencia === 'Mensual' && (
            <div style={formGroupStyle}>
              <label style={labelStyle}>Día del mes *</label>
              <input
                type="number"
                min="1"
                max="31"
                style={inputStyle(!!errors.dia_mes)}
                {...register('dia_mes', { valueAsNumber: true })}
              />
              {errors.dia_mes && <p style={errorTextStyle}>{errors.dia_mes.message}</p>}
            </div>
          )}

          <div style={formGroupStyle}>
            <label style={labelStyle}>Días de retención</label>
            <input
              type="number"
              min="1"
              max="365"
              style={inputStyle(!!errors.retencion_dias)}
              {...register('retencion_dias', { valueAsNumber: true })}
            />
            {errors.retencion_dias && <p style={errorTextStyle}>{errors.retencion_dias.message}</p>}
          </div>

          {/* Tipo de Backup */}
          <div style={formGroupStyle}>
            <label style={labelStyle}>Tipo de Backup</label>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
              <div style={optionStyle(backupType === 'completo')} onClick={() => setBackupType('completo')}>
                <div style={{ fontWeight: 600 }}>Backup Completo</div>
                <div style={{ fontSize: '12px', color: '#718096' }}>Todas las tablas</div>
              </div>
              <div style={optionStyle(backupType === 'parcial')} onClick={() => setBackupType('parcial')}>
                <div style={{ fontWeight: 600 }}>Backup Parcial</div>
                <div style={{ fontSize: '12px', color: '#718096' }}>Seleccionar tablas</div>
              </div>
            </div>
          </div>

          {/* Selección de tablas */}
          {backupType === 'parcial' && (
            <div style={formGroupStyle}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                <label style={labelStyle}>
                  <FontAwesomeIcon icon={faTable} style={{ marginRight: '6px' }} />
                  Tablas a incluir
                  {selectedTables.size > 0 && (
                    <span style={{
                      marginLeft: '8px',
                      backgroundColor: colors.doradoClasico,
                      color: 'white',
                      borderRadius: '10px',
                      padding: '2px 8px',
                      fontSize: '11px',
                    }}>
                      {selectedTables.size}
                    </span>
                  )}
                </label>
                <button
                  type="button"
                  onClick={handleSelectAll}
                  style={{ fontSize: '12px', color: colors.doradoClasico, background: 'none', border: 'none', cursor: 'pointer' }}
                >
                  {selectedTables.size === tablas.length ? 'Deseleccionar todas' : 'Seleccionar todas'}
                </button>
              </div>

              {loadingTables ? (
                <div style={{ textAlign: 'center', padding: '20px', color: '#718096' }}>Cargando tablas...</div>
              ) : tablas.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '20px', color: '#A0AEC0' }}>No hay tablas disponibles</div>
              ) : (
                <div style={tablesContainerStyle}>
                  {tablas.map((tabla) => {
                    const isSelected = selectedTables.has(tabla.table_name);
                    return (
                      <div
                        key={tabla.table_name}
                        style={tableItemStyle(isSelected)}
                        onClick={() => handleToggleTable(tabla.table_name)}
                      >
                        <FontAwesomeIcon
                          icon={isSelected ? faCheckSquare : faSquare}
                          style={{ color: isSelected ? colors.doradoClasico : '#A0AEC0', flexShrink: 0 }}
                        />
                        <span style={{ fontSize: '14px', color: isSelected ? colors.negroSuave : '#4A5568' }}>
                          {tabla.table_name}
                        </span>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          <div style={modalFooterStyle}>
            <button type="button" style={buttonStyle('secondary')} onClick={onClose}>
              Cancelar
            </button>
            <button type="submit" style={buttonStyle('primary', loading)} disabled={loading}>
              <FontAwesomeIcon icon={faSave} />
              {loading ? 'Guardando...' : config ? 'Actualizar Tarea' : 'Crear Tarea'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};